
insert into categoria (nome) values ('Celulares');
insert into categoria (nome) values ('Monitores');
insert into categoria (nome) values ('Notebooks');
insert into categoria (nome) values ('Eletrodomésticos');
insert into categoria (nome) values ('Games');
insert into categoria (nome) values ('Esportes');

insert into marca (nome) values ('Samsung');
insert into marca (nome) values ('Intel');
insert into marca (nome) values ('Lenovo');
insert into marca (nome) values ('LG');
insert into marca (nome) values ('Microsoft');
insert into marca (nome) values ('Acer');

insert into produto (nome, descricao, valor, categoria_id, marca_id, imagem, estoque, modelo, cor) values ('Smartphone Samsung Galaxy A10s 32GB 6,2"','Smartphone Galaxy A10s com designer elegante e ao mesmo tempo durável possui acabamento ergonômico e conta com sensor de impressão digital para mais segurança, o Galaxy A10s compõe câmera dupla, tudo com um campo de visão semelhante ao olho humano. O Smartphone Samsung Galaxy A10s com a câmera frontal de 8MP tornam suas fotos fabulosas nítidas e de alta resolução, e com o Foco da Selfie que desfoca suavemente o fundo, seu rosto entra em destaque.Bateria de 4.000mAh ideal para o seu estilo de vida pronta para durar o dia todo, aproveite ao máximo os melhores momentos, e não se preocupe em recarregar pois este smartphone tem carregamento rápido de 7,5W para você não perder tempo.',854.10,1,1,'../images/produtos/1.jpg', 30, 'Galaxy A10s', 'Azul');
insert into produto (nome, descricao, valor, categoria_id, marca_id, imagem, estoque, modelo, cor) values ('Smartphone Samsung Galaxy S21 Ultra Tela Infinita de 6.8"','Display AMOLED 2X muito vivo e brilhante em um smartphone Galaxy, o Galaxy S21 Ultra 5G proporciona a nossa experiência mais do que impressionante com 1.500 nits, com 100% de volume de cor para cores realistas e precisas, mesmo sob a luz do sol. Inovador sistema Dual Zoom agora dá zoom de forma mais rápida, suave e nítida do que qualquer outro Galaxy.7 E quando combinado com o novo Zoom Lock, as fotos ficam mais estáveis do que nunca. Processador mais rápido no Galaxy o primeiro processador 5 nm do Galaxy combina potência e velocidade épicas em um chipset menor essa excepcional atualização significa aprendizado mais rápido e bem mais inteligência em todos os aspectos do Galaxy S21 Ultra 5G.',6629.72,1,1,'../images/produtos/2.jpg', 30, 'Galaxy S21', 'Preto');
insert into produto (nome, descricao, valor, categoria_id, marca_id, imagem, estoque, modelo, cor) values ('Smartphone Samsung Galaxy A21s Branco 6,5"','Smartphone Galaxy A10s com designer elegante e ao mesmo tempo durável possui acabamento ergonômico e conta com sensor de impressão digital para mais segurança, o Galaxy A10s compõe câmera dupla, tudo com um campo de visão semelhante ao olho humano. O Smartphone Samsung Galaxy A10s com a câmera frontal de 8MP tornam suas fotos fabulosas nítidas e de alta resolução, e com o Foco da Selfie que desfoca suavemente o fundo, seu rosto entra em destaque.Bateria de 4.000mAh ideal para o seu estilo de vida pronta para durar o dia todo, aproveite ao máximo os melhores momentos, e não se preocupe em recarregar pois este smartphone tem carregamento rápido de 7,5W para você não perder tempo.',1863.46,1,1,'../images/produtos/3.jpg', 30, 'Galaxy A21s', 'Branco');
insert into produto (nome, descricao, valor, categoria_id, marca_id, imagem, estoque, modelo, cor) values ('Smartphone Samsung Galaxy A10s 32GB 6.2"','Display AMOLED 2X muito vivo e brilhante em um smartphone Galaxy, o Galaxy S21 Ultra 5G proporciona a nossa experiência mais do que impressionante com 1.500 nits, com 100% de volume de cor para cores realistas e precisas, mesmo sob a luz do sol. Inovador sistema Dual Zoom agora dá zoom de forma mais rápida, suave e nítida do que qualquer outro Galaxy.7 E quando combinado com o novo Zoom Lock, as fotos ficam mais estáveis do que nunca. Processador mais rápido no Galaxy o primeiro processador 5 nm do Galaxy combina potência e velocidade épicas em um chipset menor essa excepcional atualização significa aprendizado mais rápido e bem mais inteligência em todos os aspectos do Galaxy S21 Ultra 5G.',1369.91,1,1,'../images/produtos/4.jpg', 30, 'Galaxy A10s', 'Preto');

insert into produto (nome, descricao, valor, categoria_id, marca_id, imagem, estoque, modelo, cor) values ('Notebook Acer Aspire 3 15,6"','Desenvolvido para não deixar você parar, o Aspire 3 tem a tecnologia que acompanha seu estilo de vida. Execute suas tarefas diárias sem crise com a memória do Aspire 3 de 4GB e tenha imagens incríveis em qualquer situação com tela LED 15,6" e resolução HD. Teclado do tipo membrana padrão ABNT 2 de rápida resposta, com teclado numérico dedicado, deixa seu escrever confortável e anatômico. O Aspire 3 foi feito para aguentar todas as necessidades do dia.Dependendo do uso, sua bateria pode durar até 7 horas*, permitindo que você complete todas as suas tarefas!',2546.10,3,2,'../images/produtos/5.jpg', 30, 'A315-34-C5EY', 'Preto');
insert into produto (nome, descricao, valor, categoria_id, marca_id, imagem, estoque, modelo, cor) values ('Notebook Lenovo Core i5 15,8"','Com design leve e compacto o Notebook Lenovo Ideapad, S145 é fácil de transportar ideal para acompanhar o seu dia a dia independente de onde esteja, garanta agilidade e ergonomia na sua digitação com o teclado integrado do idepad S145, exemplar para trabalhar com planilhas e cálculos. A tela de 15.6 possui tecnologia com tratamento antirreflexo, e pode ser aberta em até 180° proporcionado maior versatilidade para ajustar, visando a melhor visualização e com mais segurança devido a integridade da dobradiça. Os alto falantes possuem certificação Dolby Audio e permitem aumentar o volume sem que haja distorção no som, tenha imersão sonora superior com a equalização conforme seu jeito de usar.',3520.50,3,3,'../images/produtos/6.jpg', 30, 'Ideapad S145', 'Prata');

insert into produto (nome, descricao, valor, categoria_id, marca_id, imagem, estoque, modelo, cor) values ('Monitor Curvo Samsung LED Full HD 24"','O Monitor Curvo FULL HD Samsung LED 24" C24F390 possui qualidade de imagem superior com avançada tecnologia de painel da Samsung. Com ele, você joga seus games favoritos com foco nos detalhes e sem distorções com AMD FreeSync. Além disso, ele tem tela de 1800R para maior conforto visual e perfil incrivelmente fino com design curvo estiloso.',809.25,2,1,'../images/produtos/8.jpg', 30, 'LS24D332HSXZD', 'Preto');
insert into produto (nome, descricao, valor, categoria_id, marca_id, imagem, estoque, modelo, cor) values ('Monitor LG Pro Gamer Ultrawide HD 29"','Não brinca em jogo e sabe como é importante ter uma tela de qualidade, permitindo amplo ângulo de visão e tempo e resposta em real time. Para ser um Ultra Gamer, tem que ser Ultra Wide LG. O LG UltraWide Pro Gamer oferece 30% mais tela para uma incrível imersão visual, dando a vantagem que você precisa para ganhar de seus adversários.',1349.15,2,3,'../images/produtos/9.jpg', 30, 'LC24RG50FQLMZD', 'Preto/Vermelho');

insert into produto (nome, descricao, valor, categoria_id, marca_id, imagem, estoque, modelo, cor) values ('Controle Gamer para Xbox Microsoft Sem Fio Series','Experimente o design modernizado do Xbox Wireless Controller, com superfícies esculpidas e geometria refinada para maior conforto durante o jogo. Fique no alvo com o grip texturizado e um direcional híbrido. Capture e compartilhe conteúdo perfeitamente com um botão Compartilhar dedicado. Conecte-se, jogue e alterne rapidamente entre dispositivos, incluindo Xbox Series X/S, Xbox One, PC com Windows 10, IOS e Android.',438.96,5,5,'../images/produtos/10.jpg', 30, 'Xbox Series', 'Branco');
insert into produto (nome, descricao, valor, categoria_id, marca_id, imagem, estoque, modelo, cor) values ('Notebook Acer Aspire 3 15.6"','O Notebook Acer Aspire 3 A315-23-R6DJ, junta tecnologia e possibilidade para você! Ele possui design leve e inovador. Com processador AMD Ryzen, que garante segurança, desempenho e durabilidade. Seu armazenamento de 1TB HDD SATA 3 2.5 MM RPM 5400+ Slot livre M.2 2280, compatível com SSD PCIe NVMe Gen. 3x2 de até 512GB ideal para guardar todos os seus documentos, fotos, vídeos e músicas. Possui conexões Wi-fi e BLUETOOTH , que oferecem ainda mais qualidade para o produto. E para maior segurança ele contem senhas para proteção BIOS e HDD.',3365.91,3,6,'../images/produtos/7.jpg', 30, 'Aspire 3', 'Cinza');

INSERT INTO permissao (nome) values('ROLE_ADMIN');
INSERT INTO permissao (nome) values('ROLE_USER');
--admin 123
INSERT INTO usuario(nome, username, password, cidade, endereco, telefone, cep) VALUES ('Administrador', 'admin','$2a$10$.PVIfB07x.SfMYTcToxL0.yxcLWU0GbS2NUO1W1QAvqMm/TsFhVem', 'Pato Branco', 'Rua das aaa 123', '123321', '00000-123');
INSERT INTO usuario(nome, username, password, cidade, endereco, telefone, cep) VALUES ('Teste', 'teste','$2a$10$.PVIfB07x.SfMYTcToxL0.yxcLWU0GbS2NUO1W1QAvqMm/TsFhVem', 'Pato Branco', 'Rua das aaa 123', '123321', '00000-123');

INSERT INTO usuario_permissoes(usuario_id, permissoes_id) VALUES (1, 1);
INSERT INTO usuario_permissoes(usuario_id, permissoes_id) VALUES (2, 2);


--insert into pedido (valortotal, valorfrete, tipofrete, tipopagamento, datapedido, dataalteracao) values (6900, 0, 0, 1, '2021-01-02', '2021-02-02');

--INSERT INTO produto(nome, descricao, valor, categoria_id, marca_id, image)
--SELECT 1, 'test', BulkColumn
--FROM Openrowset( Bulk 'C:\test.jpg', Single_Blob) as image

--INSERT INTO produto(nome, descricao, valor, categoria_id, marca_id, imagem) VALUES('Refrigerador 429L','Refrigerador 429L Branco, duplex....',1990.0,2,1, LOAD_FILE('C:\Users\Rafael Mello\Downloads\fotos-pw25s\1.jpg'));
